name: Deploy Home Monitor Workflow
run-name: ${{ github.actor }} deploying Home Monitor 🚀
on:
  push:
    branches:
      - main
jobs:
  Deploy-Infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"
      - name: Determine if any infrastructure has changed
        id: infrastructure-has-changed
        uses: tj-actions/changed-files@v35
        with:
          files: home_monitor_cloud/infrastructure/*
      - name: Infrastructure-Apply
        if: steps.infrastructure-has-changed.outputs.any_changed == 'true'
        run: >
          cd home_monitor_cloud/infrastructure &&
          terraform init &&
          terraform apply -auto-approve

  Deploy-functions:
    runs-on: ubuntu-latest
    needs: Deploy-Infrastructure
    permissions:
      contents: "read"

    strategy:
      matrix:
        function:
          - PublishData
          - IngestCarbonIntensityData
          - GetTotalsForHome
          - AggregateHomeTotals
          - TriggerConsumptionData
          - GetDevices
          - SendCommand
          - GetEnergyConsumption
        include:
          - function: PublishData
            service_account: ''
            path: home_monitor_cloud/functions/PublishData/**
          - function: IngestCarbonIntensityData
            service_account: ingest-data-iam-sa@home-monitor-373013.iam.gserviceaccount.com
            path: home_monitor_cloud/functions/IngestCarbonIntensityData/**
          - function: GetTotalsForHome
            service_account: get-totals-for-home-iam-sa@home-monitor-373013.iam.gserviceaccount.com
            path: home_monitor_cloud/functions/GetTotalsForHome/**
          - function: AggregateHomeTotals
            service_account: ingest-home-totals-iam-sa@home-monitor-373013.iam.gserviceaccount.com
            path: home_monitor_cloud/functions/AggregateHomeTotals/**
          - function: TriggerConsumptionData
            service_account: ''
            path: home_monitor_cloud/functions/TriggerConsumptionData/**
          - function: GetDevices
            service_account: get-devices-iam-sa@home-monitor-373013.iam.gserviceaccount.com
            path: home_monitor_cloud/functions/GetDevices/**
          - function: SendCommand
            service_account: send-command-iam-sa@home-monitor-373013.iam.gserviceaccount.com
            path: home_monitor_cloud/functions/SendCommand/**
          - function: GetEnergyConsumption
            service_account: get-energy-consumption-iam-sa@home-monitor-373013.iam.gserviceaccount.com
            path: home_monitor_cloud/functions/GetEnergyConsumption/**

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"
      - name: Deploy function
        run: |
          cd home_monitor_cloud/functions
          gcloud functions deploy ${{ matrix.function }} --runtime go119 --trigger-http --allow-unauthenticated --region europe-west1 --service-account=${{ matrix.service_account }} --project home-monitor-373013